//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailDetail
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string FiledIn { get; set; }
        public string Type { get; set; }
        public Nullable<int> MailType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ScannedCopy { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> RepliedEmailId { get; set; }
    
        public virtual MailType MailType1 { get; set; }
    }
}
