//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialBundleItem
    {
        public int Id { get; set; }
        public Nullable<int> MaterialBundleId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual MaterialBundle MaterialBundle { get; set; }
    }
}
