//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FurnitureEntities : DbContext
    {
        public FurnitureEntities()
            : base("name=FurnitureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Indent> Indents { get; set; }
        public virtual DbSet<IndentMaterial> IndentMaterials { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemLocation> ItemLocations { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobItem> JobItems { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MaterialItem> MaterialItems { get; set; }
        public virtual DbSet<Officer> Officers { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<MaterialBundle> MaterialBundles { get; set; }
        public virtual DbSet<MaterialBundleItem> MaterialBundleItems { get; set; }
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<MailDetail> MailDetails { get; set; }
        public virtual DbSet<MailType> MailTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
    }
}
