//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Officer
    {
        public int Officer_id { get; set; }
        public string Occupant_Name { get; set; }
        public string Rank { get; set; }
        public string ArmyNo { get; set; }
        public Nullable<System.DateTime> Date_MarchIn { get; set; }
        public Nullable<int> Location { get; set; }
        public string Location_Name { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> Date_Marchout { get; set; }
    
        public virtual Location Location1 { get; set; }
    }
}
